title:              Farhan Sharief's Dev Blog
email:              rhan.sharief@gmail.com
description:        May the force be with me
author:             Farhan Sharief
baseurl:            "/"
url:                "https://rhansharief.github.io/"

# Social Profiles
twitter_username:   
github_username:   rhansharief
facebook_username:  
linkedin_username: rhansharief

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
